<a href="https://colab.research.google.com/github/S-Chakraborty163/Learning-DL/blob/main/optuna_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.6.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.2)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.45)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.6.0-py3-none-any.whl (404 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 7.3 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.6.0

In [2]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [23]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-01-18 13:32:07,500] A new study created in memory with name: no-name-dc1e76ea-e259-4971-b069-9d0c8333ef7f
[I 2026-01-18 13:32:07,994] Trial 0 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 93, 'max_depth': 6}. Best is trial 0 with value: 0.7597765363128491.
[I 2026-01-18 13:32:08,611] Trial 1 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 108, 'max_depth': 15}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-01-18 13:32:09,590] Trial 2 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 177, 'max_depth': 20}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-01-18 13:32:10,298] Trial 3 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 15}. Best is trial 3 with value: 0.7783985102420856.
[I 2026-01-18 13:32:10,694] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 74, 'max_depth': 5}. Best is trial 3 with value: 0.7783985102420856.
[I 2026-01-18 13:32:11,585] Trial 5 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 172, 'max_depth': 6}. Best is trial 3 with value: 0.7783985102420856.
[I 2026-01-18 13:32:12,374] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 160, 'max_depth': 5}. Best is trial 3 with value: 0.7783985102420856.
[I 2026-01-18 13:32:13,261] Trial 7 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 164, 'max_depth': 9}. Best is trial 3 with value: 0.7783985102420856.
[I 2026-01-18 13:32:14,238] Trial 8 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 182, 'max_depth': 9}. Best is trial 3 with value: 0.7783985102420856.
[I 2026-01-18 13:32:15,013] Trial 9 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 137, 'max_depth': 10}. Best is trial 3 with value: 0.7783985102420856.
[I 2026-01-18 13:32:15,339] Trial 10 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 57, 'max_depth': 15}. Best is trial 3 with value: 0.7783985102420856.
[I 2026-01-18 13:32:15,991] Trial 11 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 112, 'max_depth': 16}. Best is trial 3 with value: 0.7783985102420856.
[I 2026-01-18 13:32:17,103] Trial 12 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 128, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:18,355] Trial 13 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 140, 'max_depth': 18}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:19,184] Trial 14 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 135, 'max_depth': 13}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:20,268] Trial 15 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 197, 'max_depth': 12}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:20,998] Trial 16 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 114, 'max_depth': 18}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:21,827] Trial 17 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 150, 'max_depth': 13}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:22,349] Trial 18 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 90, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:23,061] Trial 19 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 124, 'max_depth': 20}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:23,572] Trial 20 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 90, 'max_depth': 14}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:24,211] Trial 21 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 111, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:24,918] Trial 22 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 122, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:25,500] Trial 23 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 100, 'max_depth': 11}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:26,335] Trial 24 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 148, 'max_depth': 15}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:26,764] Trial 25 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 75, 'max_depth': 18}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:27,067] Trial 26 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 53, 'max_depth': 19}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-01-18 13:32:27,519] Trial 27 finished with value: 0.7839851024208566 and parameters: {'n_estimators': 73, 'max_depth': 18}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:27,945] Trial 28 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 74, 'max_depth': 19}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:28,381] Trial 29 finished with value: 0.7839851024208566 and parameters: {'n_estimators': 73, 'max_depth': 18}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:28,930] Trial 30 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 67, 'max_depth': 17}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:29,657] Trial 31 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 80, 'max_depth': 19}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:30,204] Trial 32 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 62, 'max_depth': 18}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:31,466] Trial 33 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 82, 'max_depth': 20}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:32,722] Trial 34 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 104, 'max_depth': 16}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:33,587] Trial 35 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 98, 'max_depth': 3}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:34,484] Trial 36 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 68, 'max_depth': 14}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:35,235] Trial 37 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 82, 'max_depth': 18}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:35,946] Trial 38 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 71, 'max_depth': 20}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:36,541] Trial 39 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 60, 'max_depth': 17}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:37,347] Trial 40 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 92, 'max_depth': 19}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:37,772] Trial 41 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 17}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:38,335] Trial 42 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 66, 'max_depth': 16}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:39,075] Trial 43 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 79, 'max_depth': 18}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:39,577] Trial 44 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 63, 'max_depth': 14}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:40,417] Trial 45 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 85, 'max_depth': 17}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:41,124] Trial 46 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 72, 'max_depth': 8}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:43,770] Trial 47 finished with value: 0.7839851024208566 and parameters: {'n_estimators': 119, 'max_depth': 15}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:46,595] Trial 48 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 143, 'max_depth': 16}. Best is trial 27 with value: 0.7839851024208566.
[I 2026-01-18 13:32:47,886] Trial 49 finished with value: 0.7839851024208566 and parameters: {'n_estimators': 119, 'max_depth': 15}. Best is trial 27 with value: 0.7839851024208566.

In [24]:
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7839851024208566
Best hyperparameters: {'n_estimators': 73, 'max_depth': 18}

In [25]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

## Samplers in Optuna

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [10]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-01-18 13:27:55,638] A new study created in memory with name: no-name-bfa1f47d-4153-42a0-b054-939922f0c9a8
[I 2026-01-18 13:27:55,939] Trial 0 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 53, 'max_depth': 12}. Best is trial 0 with value: 0.7597765363128492.
[I 2026-01-18 13:27:57,154] Trial 1 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 182, 'max_depth': 5}. Best is trial 1 with value: 0.7635009310986964.
[I 2026-01-18 13:27:58,112] Trial 2 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 111, 'max_depth': 18}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:27:59,279] Trial 3 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 166, 'max_depth': 11}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:27:59,815] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 103, 'max_depth': 5}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:28:00,730] Trial 5 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 162, 'max_depth': 16}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:28:01,296] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 18}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:28:02,045] Trial 7 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 138, 'max_depth': 10}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:28:03,032] Trial 8 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 190, 'max_depth': 7}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:28:04,095] Trial 9 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 196, 'max_depth': 20}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:28:04,961] Trial 10 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 154, 'max_depth': 16}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:28:05,574] Trial 11 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 113, 'max_depth': 16}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:28:06,477] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 166, 'max_depth': 17}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:28:06,981] Trial 13 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 89, 'max_depth': 12}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:28:07,379] Trial 14 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 81, 'max_depth': 4}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:28:07,699] Trial 15 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 55, 'max_depth': 9}. Best is trial 2 with value: 0.7765363128491621.
[I 2026-01-18 13:28:08,110] Trial 16 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 72, 'max_depth': 18}. Best is trial 16 with value: 0.7783985102420857.
[I 2026-01-18 13:28:09,325] Trial 17 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 192, 'max_depth': 7}. Best is trial 16 with value: 0.7783985102420857.
[I 2026-01-18 13:28:10,202] Trial 18 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 106, 'max_depth': 7}. Best is trial 16 with value: 0.7783985102420857.
[I 2026-01-18 13:28:11,121] Trial 19 finished with value: 0.7579143389199255 and parameters: {'n_estimators': 118, 'max_depth': 3}. Best is trial 16 with value: 0.7783985102420857.
[I 2026-01-18 13:28:11,634] Trial 20 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 80, 'max_depth': 19}. Best is trial 16 with value: 0.7783985102420857.
[I 2026-01-18 13:28:12,206] Trial 21 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 105, 'max_depth': 9}. Best is trial 16 with value: 0.7783985102420857.
[I 2026-01-18 13:28:12,525] Trial 22 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 61, 'max_depth': 5}. Best is trial 16 with value: 0.7783985102420857.
[I 2026-01-18 13:28:13,126] Trial 23 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 107, 'max_depth': 12}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:13,679] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 102, 'max_depth': 18}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:13,964] Trial 25 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 56, 'max_depth': 3}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:14,279] Trial 26 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 62, 'max_depth': 3}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:14,952] Trial 27 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 126, 'max_depth': 9}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:15,885] Trial 28 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 169, 'max_depth': 12}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:16,693] Trial 29 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 147, 'max_depth': 17}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:17,160] Trial 30 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 96, 'max_depth': 3}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:17,958] Trial 31 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 147, 'max_depth': 15}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:18,485] Trial 32 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 104, 'max_depth': 4}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:19,322] Trial 33 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 153, 'max_depth': 15}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:19,876] Trial 34 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 101, 'max_depth': 10}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:20,350] Trial 35 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 84, 'max_depth': 11}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:20,881] Trial 36 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 96, 'max_depth': 20}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:22,079] Trial 37 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 165, 'max_depth': 15}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:23,333] Trial 38 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 128, 'max_depth': 13}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:24,951] Trial 39 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 144, 'max_depth': 7}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:25,612] Trial 40 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 119, 'max_depth': 11}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:26,183] Trial 41 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 114, 'max_depth': 5}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:27,005] Trial 42 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 148, 'max_depth': 15}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:27,551] Trial 43 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 99, 'max_depth': 18}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:28,529] Trial 44 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 176, 'max_depth': 20}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:29,426] Trial 45 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 168, 'max_depth': 9}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:30,022] Trial 46 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 109, 'max_depth': 8}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:30,441] Trial 47 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 78, 'max_depth': 9}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:31,280] Trial 48 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 152, 'max_depth': 14}. Best is trial 23 with value: 0.7802607076350093.
[I 2026-01-18 13:28:32,146] Trial 49 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 157, 'max_depth': 15}. Best is trial 23 with value: 0.7802607076350093.

In [11]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 107, 'max_depth': 12}

In [12]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

In [13]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [14]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-01-18 13:29:06,057] A new study created in memory with name: no-name-93c3b29f-a267-4d44-8b0d-ac87e951e224
[I 2026-01-18 13:29:06,588] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-01-18 13:29:07,389] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-01-18 13:29:07,696] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-01-18 13:29:08,246] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-01-18 13:29:08,974] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-01-18 13:29:09,421] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-01-18 13:29:10,648] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-01-18 13:29:11,602] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-01-18 13:29:12,425] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-01-18 13:29:13,514] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-01-18 13:29:14,627] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-01-18 13:29:15,723] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-01-18 13:29:16,729] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-01-18 13:29:16,997] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-01-18 13:29:17,557] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-01-18 13:29:17,840] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [15]:

print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [16]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Optuna Visualizations(On TPE Sampler case)

In [26]:
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [27]:
# 1. Optimization History
plot_optimization_history(study).show()

In [28]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [29]:
# 3. Slice Plot
plot_slice(study).show()

In [30]:
# 4. Contour Plot
plot_contour(study).show()

In [31]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

## Optimizing Multiple ML Models

In [32]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [33]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [34]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-01-18 13:40:09,159] A new study created in memory with name: no-name-8d020ccc-a8c0-4bb3-8403-352edfe5334e
[I 2026-01-18 13:40:12,069] Trial 0 finished with value: 0.7728119180633147 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 216, 'learning_rate': 0.01150874931646131, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:13,132] Trial 1 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 130, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:13,190] Trial 2 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.10915854557383498, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:15,900] Trial 3 finished with value: 0.7318435754189944 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 118, 'learning_rate': 0.04323194397308193, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:16,742] Trial 4 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 170, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:18,057] Trial 5 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 290, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:20,204] Trial 6 finished with value: 0.7299813780260708 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 109, 'learning_rate': 0.03141651531856107, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:26,729] Trial 7 finished with value: 0.739292364990689 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 214, 'learning_rate': 0.03493263917604818, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:27,380] Trial 8 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 147, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:27,417] Trial 9 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 9.061560684298103, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:29,855] Trial 10 finished with value: 0.7616387337057727 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 230, 'learning_rate': 0.010247730099834217, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:30,106] Trial 11 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 53, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:32,701] Trial 12 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 202, 'learning_rate': 0.2107363197369814, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:33,952] Trial 13 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 280, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-01-18 13:40:34,217] Trial 14 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 67.44350244441758, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-01-18 13:40:34,565] Trial 15 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 98.16451833390623, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-01-18 13:40:34,895] Trial 16 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 86.97349641264228, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-01-18 13:40:35,255] Trial 17 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 96.66143334718258, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-01-18 13:40:35,345] Trial 18 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.606552554519277, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-01-18 13:40:35,411] Trial 19 finished with value: 0.7132216014897579 and parameters: {'classifier': 'SVM', 'C': 98.79680362060235, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-01-18 13:40:35,448] Trial 20 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7569404842730538, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:35,479] Trial 21 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4241567329665646, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:35,515] Trial 22 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.2639592124033356, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:35,626] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 18.548461537302607, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:35,662] Trial 24 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.50429029518732, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:35,695] Trial 25 finished with value: 0.690875232774674 and parameters: {'classifier': 'SVM', 'C': 30.639216792715857, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:35,731] Trial 26 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 3.761840306243502, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:35,763] Trial 27 finished with value: 0.7392923649906891 and parameters: {'classifier': 'SVM', 'C': 0.41434527425393347, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:35,885] Trial 28 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 29.52728442170625, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:36,050] Trial 29 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 42.385035900933964, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:36,103] Trial 30 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.83521254470229, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:36,377] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 66.77693725375948, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:36,681] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 44.51176139146651, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:37,010] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 58.543144779001196, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:37,058] Trial 34 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.1134929144454928, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:37,122] Trial 35 finished with value: 0.7392923649906891 and parameters: {'classifier': 'SVM', 'C': 21.718827011753834, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:37,168] Trial 36 finished with value: 0.7225325884543761 and parameters: {'classifier': 'SVM', 'C': 0.2628920730788302, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:37,258] Trial 37 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 8.378543159024554, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:37,702] Trial 38 finished with value: 0.7616387337057727 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 52, 'learning_rate': 0.23987579624291733, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:39,451] Trial 39 finished with value: 0.7560521415270017 and parameters: {'classifier': 'RandomForest', 'n_estimators': 259, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:39,486] Trial 40 finished with value: 0.7057728119180634 and parameters: {'classifier': 'SVM', 'C': 76.08997252163613, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:39,862] Trial 41 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 85.53553314424438, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:40,193] Trial 42 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 98.72787023187554, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:40,392] Trial 43 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 45.71600962830952, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:42,160] Trial 44 finished with value: 0.7318435754189944 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 90, 'learning_rate': 0.10191737250276947, 'max_depth': 17, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:43,040] Trial 45 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 170, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:43,080] Trial 46 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.101746756325464, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:43,114] Trial 47 finished with value: 0.685288640595903 and parameters: {'classifier': 'SVM', 'C': 53.364325528440474, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:44,442] Trial 48 finished with value: 0.7579143389199254 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 249, 'learning_rate': 0.09631530854768447, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:44,585] Trial 49 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 31.082036638121238, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:45,100] Trial 50 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 89, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:45,170] Trial 51 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 11.038525856937229, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:45,266] Trial 52 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 16.754455467117477, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 20 with value: 0.7858472998137803.
[I 2026-01-18 13:40:45,296] Trial 53 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11323498569454386, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:45,327] Trial 54 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 0.11519699771117663, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:45,356] Trial 55 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1676094414776564, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:45,389] Trial 56 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10170143070616154, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:45,419] Trial 57 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1064660859789452, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:45,448] Trial 58 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13682217782137515, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:48,297] Trial 59 finished with value: 0.7541899441340781 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 195, 'learning_rate': 0.0211507510145632, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:48,327] Trial 60 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10717285500158728, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:48,356] Trial 61 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1071150841262307, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:48,386] Trial 62 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10221055698248126, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:48,416] Trial 63 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1657599113303682, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:48,447] Trial 64 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17024465547546114, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:48,484] Trial 65 finished with value: 0.756052141527002 and parameters: {'classifier': 'SVM', 'C': 0.1570666107729208, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:48,513] Trial 66 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24740124199378716, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:49,243] Trial 67 finished with value: 0.7783985102420857 and parameters: {'classifier': 'RandomForest', 'n_estimators': 146, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:49,293] Trial 68 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2579113969064897, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:49,340] Trial 69 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12977717310548567, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:49,403] Trial 70 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.14527795875227612, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:49,447] Trial 71 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10018569282175019, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:49,488] Trial 72 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2121678107164252, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:49,535] Trial 73 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.38758430703799013, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:49,579] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13227695250658061, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:49,627] Trial 75 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13602343777552625, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:49,683] Trial 76 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 0.1390978397953058, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:49,730] Trial 77 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2011998847196472, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:49,791] Trial 78 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.330110229820327, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:49,840] Trial 79 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.554758719489498, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 53 with value: 0.7895716945996275.
[I 2026-01-18 13:40:51,509] Trial 80 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 75, 'learning_rate': 0.07988680145323843, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 53 with value: 0.7895716945996275.

In [35]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.11323498569454386, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

In [36]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.772812,2026-01-18 13:40:09.162079,2026-01-18 13:40:12.069746,0 days 00:00:02.907667,NaN,NaN,GradientBoosting,NaN,NaN,0.011509,13.0,7.0,3.0,216.0,COMPLETE
1,1,0.761639,2026-01-18 13:40:12.070935,2026-01-18 13:40:13.132483,0 days 00:00:01.061548,NaN,True,RandomForest,NaN,NaN,NaN,9.0,7.0,5.0,130.0,COMPLETE
2,2,0.765363,2026-01-18 13:40:13.134340,2026-01-18 13:40:13.190614,0 days 00:00:00.056274,0.109159,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,0.731844,2026-01-18 13:40:13.191707,2026-01-18 13:40:15.900469,0 days 00:00:02.708762,NaN,NaN,GradientBoosting,NaN,NaN,0.043232,10.0,2.0,5.0,118.0,COMPLETE
4,4,0.759777,2026-01-18 13:40:15.901353,2026-01-18 13:40:16.742538,0 days 00:00:00.841185,NaN,True,RandomForest,NaN,NaN,NaN,6.0,10.0,10.0,170.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.772812,2026-01-18 13:40:53.156335,2026-01-18 13:40:53.200017,0 days 00:00:00.043682,0.170083,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.728119,2026-01-18 13:40:53.200861,2026-01-18 13:40:53.239536,0 days 00:00:00.038675,0.314725,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.789572,2026-01-18 13:40:53.240323,2026-01-18 13:40:53.269170,0 days 00:00:00.028847,0.125871,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.787709,2026-01-18 13:40:53.270001,2026-01-18 13:40:53.301025,0 days 00:00:00.031024,0.163633,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.741155,2026-01-18 13:40:53.301946,2026-01-18 13:40:56.740678,0 days 00:00:03.438732,NaN,NaN,GradientBoosting,NaN,NaN,0.149572,11.0,6.0,6.0,296.0,COMPLETE

In [37]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 77
GradientBoosting    12
RandomForest        11
Name: count, dtype: int64

In [38]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.748759
RandomForest        0.763840
SVM                 0.774989
Name: value, dtype: float64

In [39]:
# 1. Optimization History
plot_optimization_history(study).show()

In [40]:
# 3. Slice Plot
plot_slice(study).show()

In [41]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()